In [7]:
import numpy as np
lis = eval(input())

print(np.all(lis))

False


In [8]:
print(np.any(lis))

True


In [12]:
lis2 = eval(input())
print(np.equal(lis,lis2))
print(np.allclose(lis,lis2))

[ True  True  True False]
False


In [13]:
arr1 = np.zeros(10)
arr2 = np.ones(10)
arr3 = np.ones(10)*5
print(arr1,arr2,arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [15]:
arr4 = np.arange(30,71,1)
print(arr4)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [16]:
Identity = np.identity(3)
print(Identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
print(np.random.random())

0.19493849490599502


In [28]:
print(np.random.normal(0,1,15))

[-0.74470971 -0.99923231  1.43414425  1.6788804   0.22341363 -1.47761531
 -0.32462667 -1.14611516 -0.80644415  0.07664481 -1.14893881  1.0157285
 -0.038297   -0.73610684  0.08609465]


In [31]:
rand = np.arange(15,56)
print(rand[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [33]:
print(np.random.randint(0,11,5))

[0 2 1 8 2]


In [34]:
mat = np.ones((10,10))
mat[1:-1,1:-1] = 0
print(mat)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [42]:
print(np.diag([1,2,3,4,5]))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [43]:
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [47]:
np.savez("temp.npz",lis=lis,lis2=lis2)

with np.load("temp.npz") as data:
    print(data['lis'],data['lis2'])

[1 2 3 0] [1.e+00 2.e+00 3.e+00 1.e-05]


In [48]:
print(np.random.rand(40))

[0.41835258 0.54783516 0.5848733  0.71793799 0.63502484 0.66803484
 0.01458758 0.47288093 0.5598258  0.61117195 0.06024916 0.33734381
 0.43503994 0.90482356 0.24608773 0.28333021 0.02998408 0.33676553
 0.70747746 0.70475888 0.09585239 0.17401861 0.3755944  0.63854257
 0.61339495 0.92874531 0.09185771 0.36479358 0.57432507 0.61195853
 0.56000877 0.25839618 0.56580063 0.31952904 0.0402397  0.6722028
 0.0655134  0.07688981 0.77733089 0.01092332]


In [52]:
k=eval(input())
lis = np.array(lis)
print(lis[lis > k])
print(lis[lis < k])

[3]
[1 0]
